import type { Metadata } from "next";
import { Roboto, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { AuthProvider } from "@/contexts/authContext";

const primaryFont = Nunito({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-primary" });

const secondaryFont = Roboto({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-secondary" });

export const metadata: Metadata = {
  title: "Tech Pulse",
  description: "Generated by create next app",
  icons:{
    icon: "/images/rayito.png",
      
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
    <html lang="en">
      <body className={primaryFont.className}>
      <Navbar />
      <main>{children}</main>
      <Footer />
      </body>
    </html>
    </AuthProvider>
  );
}
